# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1270/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1270/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dylan/projects/reporting-daemon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dylan/projects/reporting-daemon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1270/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1270/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dylan/projects/reporting-daemon/CMakeFiles /home/dylan/projects/reporting-daemon//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dylan/projects/reporting-daemon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named reporting_daemon

# Build rule for target.
reporting_daemon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reporting_daemon
.PHONY : reporting_daemon

# fast build rule for target.
reporting_daemon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/build
.PHONY : reporting_daemon/fast

daemon_tasks/check_directory.o: daemon_tasks/check_directory.c.o
.PHONY : daemon_tasks/check_directory.o

# target to build an object file
daemon_tasks/check_directory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/check_directory.c.o
.PHONY : daemon_tasks/check_directory.c.o

daemon_tasks/check_directory.i: daemon_tasks/check_directory.c.i
.PHONY : daemon_tasks/check_directory.i

# target to preprocess a source file
daemon_tasks/check_directory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/check_directory.c.i
.PHONY : daemon_tasks/check_directory.c.i

daemon_tasks/check_directory.s: daemon_tasks/check_directory.c.s
.PHONY : daemon_tasks/check_directory.s

# target to generate assembly for a file
daemon_tasks/check_directory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/check_directory.c.s
.PHONY : daemon_tasks/check_directory.c.s

daemon_tasks/transfer/backup_files.o: daemon_tasks/transfer/backup_files.c.o
.PHONY : daemon_tasks/transfer/backup_files.o

# target to build an object file
daemon_tasks/transfer/backup_files.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/backup_files.c.o
.PHONY : daemon_tasks/transfer/backup_files.c.o

daemon_tasks/transfer/backup_files.i: daemon_tasks/transfer/backup_files.c.i
.PHONY : daemon_tasks/transfer/backup_files.i

# target to preprocess a source file
daemon_tasks/transfer/backup_files.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/backup_files.c.i
.PHONY : daemon_tasks/transfer/backup_files.c.i

daemon_tasks/transfer/backup_files.s: daemon_tasks/transfer/backup_files.c.s
.PHONY : daemon_tasks/transfer/backup_files.s

# target to generate assembly for a file
daemon_tasks/transfer/backup_files.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/backup_files.c.s
.PHONY : daemon_tasks/transfer/backup_files.c.s

daemon_tasks/transfer/lock_directories.o: daemon_tasks/transfer/lock_directories.c.o
.PHONY : daemon_tasks/transfer/lock_directories.o

# target to build an object file
daemon_tasks/transfer/lock_directories.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/lock_directories.c.o
.PHONY : daemon_tasks/transfer/lock_directories.c.o

daemon_tasks/transfer/lock_directories.i: daemon_tasks/transfer/lock_directories.c.i
.PHONY : daemon_tasks/transfer/lock_directories.i

# target to preprocess a source file
daemon_tasks/transfer/lock_directories.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/lock_directories.c.i
.PHONY : daemon_tasks/transfer/lock_directories.c.i

daemon_tasks/transfer/lock_directories.s: daemon_tasks/transfer/lock_directories.c.s
.PHONY : daemon_tasks/transfer/lock_directories.s

# target to generate assembly for a file
daemon_tasks/transfer/lock_directories.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/lock_directories.c.s
.PHONY : daemon_tasks/transfer/lock_directories.c.s

daemon_tasks/transfer/transfer_reports.o: daemon_tasks/transfer/transfer_reports.c.o
.PHONY : daemon_tasks/transfer/transfer_reports.o

# target to build an object file
daemon_tasks/transfer/transfer_reports.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/transfer_reports.c.o
.PHONY : daemon_tasks/transfer/transfer_reports.c.o

daemon_tasks/transfer/transfer_reports.i: daemon_tasks/transfer/transfer_reports.c.i
.PHONY : daemon_tasks/transfer/transfer_reports.i

# target to preprocess a source file
daemon_tasks/transfer/transfer_reports.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/transfer_reports.c.i
.PHONY : daemon_tasks/transfer/transfer_reports.c.i

daemon_tasks/transfer/transfer_reports.s: daemon_tasks/transfer/transfer_reports.c.s
.PHONY : daemon_tasks/transfer/transfer_reports.s

# target to generate assembly for a file
daemon_tasks/transfer/transfer_reports.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/transfer_reports.c.s
.PHONY : daemon_tasks/transfer/transfer_reports.c.s

daemon_tasks/transfer/transfer_uploads.o: daemon_tasks/transfer/transfer_uploads.c.o
.PHONY : daemon_tasks/transfer/transfer_uploads.o

# target to build an object file
daemon_tasks/transfer/transfer_uploads.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/transfer_uploads.c.o
.PHONY : daemon_tasks/transfer/transfer_uploads.c.o

daemon_tasks/transfer/transfer_uploads.i: daemon_tasks/transfer/transfer_uploads.c.i
.PHONY : daemon_tasks/transfer/transfer_uploads.i

# target to preprocess a source file
daemon_tasks/transfer/transfer_uploads.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/transfer_uploads.c.i
.PHONY : daemon_tasks/transfer/transfer_uploads.c.i

daemon_tasks/transfer/transfer_uploads.s: daemon_tasks/transfer/transfer_uploads.c.s
.PHONY : daemon_tasks/transfer/transfer_uploads.s

# target to generate assembly for a file
daemon_tasks/transfer/transfer_uploads.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/transfer_uploads.c.s
.PHONY : daemon_tasks/transfer/transfer_uploads.c.s

daemon_tasks/transfer/unlock_directories.o: daemon_tasks/transfer/unlock_directories.c.o
.PHONY : daemon_tasks/transfer/unlock_directories.o

# target to build an object file
daemon_tasks/transfer/unlock_directories.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/unlock_directories.c.o
.PHONY : daemon_tasks/transfer/unlock_directories.c.o

daemon_tasks/transfer/unlock_directories.i: daemon_tasks/transfer/unlock_directories.c.i
.PHONY : daemon_tasks/transfer/unlock_directories.i

# target to preprocess a source file
daemon_tasks/transfer/unlock_directories.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/unlock_directories.c.i
.PHONY : daemon_tasks/transfer/unlock_directories.c.i

daemon_tasks/transfer/unlock_directories.s: daemon_tasks/transfer/unlock_directories.c.s
.PHONY : daemon_tasks/transfer/unlock_directories.s

# target to generate assembly for a file
daemon_tasks/transfer/unlock_directories.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/daemon_tasks/transfer/unlock_directories.c.s
.PHONY : daemon_tasks/transfer/unlock_directories.c.s

event_logging/reporting_event.o: event_logging/reporting_event.c.o
.PHONY : event_logging/reporting_event.o

# target to build an object file
event_logging/reporting_event.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/event_logging/reporting_event.c.o
.PHONY : event_logging/reporting_event.c.o

event_logging/reporting_event.i: event_logging/reporting_event.c.i
.PHONY : event_logging/reporting_event.i

# target to preprocess a source file
event_logging/reporting_event.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/event_logging/reporting_event.c.i
.PHONY : event_logging/reporting_event.c.i

event_logging/reporting_event.s: event_logging/reporting_event.c.s
.PHONY : event_logging/reporting_event.s

# target to generate assembly for a file
event_logging/reporting_event.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/event_logging/reporting_event.c.s
.PHONY : event_logging/reporting_event.c.s

event_logging/watch_directory.o: event_logging/watch_directory.c.o
.PHONY : event_logging/watch_directory.o

# target to build an object file
event_logging/watch_directory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/event_logging/watch_directory.c.o
.PHONY : event_logging/watch_directory.c.o

event_logging/watch_directory.i: event_logging/watch_directory.c.i
.PHONY : event_logging/watch_directory.i

# target to preprocess a source file
event_logging/watch_directory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/event_logging/watch_directory.c.i
.PHONY : event_logging/watch_directory.c.i

event_logging/watch_directory.s: event_logging/watch_directory.c.s
.PHONY : event_logging/watch_directory.s

# target to generate assembly for a file
event_logging/watch_directory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/event_logging/watch_directory.c.s
.PHONY : event_logging/watch_directory.c.s

ipc/listen_task_completion.o: ipc/listen_task_completion.c.o
.PHONY : ipc/listen_task_completion.o

# target to build an object file
ipc/listen_task_completion.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/ipc/listen_task_completion.c.o
.PHONY : ipc/listen_task_completion.c.o

ipc/listen_task_completion.i: ipc/listen_task_completion.c.i
.PHONY : ipc/listen_task_completion.i

# target to preprocess a source file
ipc/listen_task_completion.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/ipc/listen_task_completion.c.i
.PHONY : ipc/listen_task_completion.c.i

ipc/listen_task_completion.s: ipc/listen_task_completion.c.s
.PHONY : ipc/listen_task_completion.s

# target to generate assembly for a file
ipc/listen_task_completion.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/ipc/listen_task_completion.c.s
.PHONY : ipc/listen_task_completion.c.s

ipc/log_task_completion.o: ipc/log_task_completion.c.o
.PHONY : ipc/log_task_completion.o

# target to build an object file
ipc/log_task_completion.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/ipc/log_task_completion.c.o
.PHONY : ipc/log_task_completion.c.o

ipc/log_task_completion.i: ipc/log_task_completion.c.i
.PHONY : ipc/log_task_completion.i

# target to preprocess a source file
ipc/log_task_completion.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/ipc/log_task_completion.c.i
.PHONY : ipc/log_task_completion.c.i

ipc/log_task_completion.s: ipc/log_task_completion.c.s
.PHONY : ipc/log_task_completion.s

# target to generate assembly for a file
ipc/log_task_completion.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/ipc/log_task_completion.c.s
.PHONY : ipc/log_task_completion.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/main.c.s
.PHONY : main.c.s

signals/handle_interrupt.o: signals/handle_interrupt.c.o
.PHONY : signals/handle_interrupt.o

# target to build an object file
signals/handle_interrupt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/signals/handle_interrupt.c.o
.PHONY : signals/handle_interrupt.c.o

signals/handle_interrupt.i: signals/handle_interrupt.c.i
.PHONY : signals/handle_interrupt.i

# target to preprocess a source file
signals/handle_interrupt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/signals/handle_interrupt.c.i
.PHONY : signals/handle_interrupt.c.i

signals/handle_interrupt.s: signals/handle_interrupt.c.s
.PHONY : signals/handle_interrupt.s

# target to generate assembly for a file
signals/handle_interrupt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/signals/handle_interrupt.c.s
.PHONY : signals/handle_interrupt.c.s

time/reporting_time.o: time/reporting_time.c.o
.PHONY : time/reporting_time.o

# target to build an object file
time/reporting_time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/time/reporting_time.c.o
.PHONY : time/reporting_time.c.o

time/reporting_time.i: time/reporting_time.c.i
.PHONY : time/reporting_time.i

# target to preprocess a source file
time/reporting_time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/time/reporting_time.c.i
.PHONY : time/reporting_time.c.i

time/reporting_time.s: time/reporting_time.c.s
.PHONY : time/reporting_time.s

# target to generate assembly for a file
time/reporting_time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reporting_daemon.dir/build.make CMakeFiles/reporting_daemon.dir/time/reporting_time.c.s
.PHONY : time/reporting_time.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... reporting_daemon"
	@echo "... daemon_tasks/check_directory.o"
	@echo "... daemon_tasks/check_directory.i"
	@echo "... daemon_tasks/check_directory.s"
	@echo "... daemon_tasks/transfer/backup_files.o"
	@echo "... daemon_tasks/transfer/backup_files.i"
	@echo "... daemon_tasks/transfer/backup_files.s"
	@echo "... daemon_tasks/transfer/lock_directories.o"
	@echo "... daemon_tasks/transfer/lock_directories.i"
	@echo "... daemon_tasks/transfer/lock_directories.s"
	@echo "... daemon_tasks/transfer/transfer_reports.o"
	@echo "... daemon_tasks/transfer/transfer_reports.i"
	@echo "... daemon_tasks/transfer/transfer_reports.s"
	@echo "... daemon_tasks/transfer/transfer_uploads.o"
	@echo "... daemon_tasks/transfer/transfer_uploads.i"
	@echo "... daemon_tasks/transfer/transfer_uploads.s"
	@echo "... daemon_tasks/transfer/unlock_directories.o"
	@echo "... daemon_tasks/transfer/unlock_directories.i"
	@echo "... daemon_tasks/transfer/unlock_directories.s"
	@echo "... event_logging/reporting_event.o"
	@echo "... event_logging/reporting_event.i"
	@echo "... event_logging/reporting_event.s"
	@echo "... event_logging/watch_directory.o"
	@echo "... event_logging/watch_directory.i"
	@echo "... event_logging/watch_directory.s"
	@echo "... ipc/listen_task_completion.o"
	@echo "... ipc/listen_task_completion.i"
	@echo "... ipc/listen_task_completion.s"
	@echo "... ipc/log_task_completion.o"
	@echo "... ipc/log_task_completion.i"
	@echo "... ipc/log_task_completion.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... signals/handle_interrupt.o"
	@echo "... signals/handle_interrupt.i"
	@echo "... signals/handle_interrupt.s"
	@echo "... time/reporting_time.o"
	@echo "... time/reporting_time.i"
	@echo "... time/reporting_time.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

